"""
Abstract Base Classes for Module A: Issuer 360.

This module defines the interfaces for AI-driven qualitative analysis.
Concrete implementations will integrate LLM agents for:
- Credit profile generation
- Financial report analysis
- News sentiment analysis
- Covenant document parsing

Design Principle: These ABCs allow future LLM integrations without
modifying the core application architecture.
"""

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Any, Dict, List, Optional


class CreditRating(Enum):
    """Standard credit rating scale."""
    AAA = "AAA"
    AA_PLUS = "AA+"
    AA = "AA"
    AA_MINUS = "AA-"
    A_PLUS = "A+"
    A = "A"
    A_MINUS = "A-"
    BBB_PLUS = "BBB+"
    BBB = "BBB"
    BBB_MINUS = "BBB-"
    BB_PLUS = "BB+"
    BB = "BB"
    BB_MINUS = "BB-"
    B_PLUS = "B+"
    B = "B"
    B_MINUS = "B-"
    CCC = "CCC"
    CC = "CC"
    C = "C"
    D = "D"
    NR = "NR"  # Not Rated


class SentimentScore(Enum):
    """Sentiment analysis result."""
    VERY_POSITIVE = 2
    POSITIVE = 1
    NEUTRAL = 0
    NEGATIVE = -1
    VERY_NEGATIVE = -2


@dataclass
class CreditProfile:
    """
    Comprehensive credit profile for an issuer.

    Generated by combining quantitative metrics with
    AI-driven qualitative analysis.
    """
    issuer_id: str
    issuer_name: str
    sector: str
    rating_agency_rating: Optional[CreditRating] = None
    internal_rating: Optional[CreditRating] = None
    rating_outlook: Optional[str] = None  # Positive, Stable, Negative

    # Quantitative Metrics
    leverage_ratio: Optional[float] = None
    interest_coverage: Optional[float] = None
    debt_to_ebitda: Optional[float] = None
    current_ratio: Optional[float] = None

    # AI-Generated Insights
    executive_summary: Optional[str] = None
    key_risks: List[str] = field(default_factory=list)
    key_strengths: List[str] = field(default_factory=list)
    news_sentiment: Optional[SentimentScore] = None
    covenant_status: Optional[str] = None

    # Metadata
    last_updated: datetime = field(default_factory=datetime.now)
    confidence_score: float = 0.0  # 0-1 confidence in the analysis
    sources: List[str] = field(default_factory=list)


@dataclass
class DocumentAnalysisResult:
    """Result of analyzing a financial document."""
    document_id: str
    document_type: str  # 10-K, 10-Q, Earnings Call, etc.
    issuer_id: str

    # Extracted Information
    key_metrics: Dict[str, Any] = field(default_factory=dict)
    summary: Optional[str] = None
    sentiment: Optional[SentimentScore] = None

    # Red Flags / Highlights
    red_flags: List[str] = field(default_factory=list)
    positive_signals: List[str] = field(default_factory=list)

    # Metadata
    processing_time_ms: int = 0
    model_version: str = ""
    confidence_score: float = 0.0


@dataclass
class NewsItem:
    """A news item relevant to an issuer."""
    headline: str
    source: str
    published_date: datetime
    url: Optional[str] = None
    content: Optional[str] = None
    sentiment: Optional[SentimentScore] = None
    relevance_score: float = 0.0
    issuers_mentioned: List[str] = field(default_factory=list)


class BaseAnalyzer(ABC):
    """
    Abstract base class for all analysis components.

    Provides common interface for initialization, configuration,
    and health checks.
    """

    @abstractmethod
    def initialize(self, config: Dict[str, Any]) -> None:
        """
        Initialize the analyzer with configuration.

        Args:
            config: Configuration dictionary (API keys, model settings, etc.)
        """
        pass

    @abstractmethod
    def health_check(self) -> bool:
        """
        Check if the analyzer is properly configured and operational.

        Returns:
            True if operational, False otherwise
        """
        pass

    @property
    @abstractmethod
    def model_info(self) -> Dict[str, str]:
        """
        Get information about the underlying model.

        Returns:
            Dictionary with model name, version, provider, etc.
        """
        pass


class BaseCreditProfiler(BaseAnalyzer):
    """
    Abstract base class for credit profile generation.

    Implementations should integrate with LLM providers to
    generate comprehensive issuer credit profiles.
    """

    @abstractmethod
    def generate_profile(
        self,
        issuer_id: str,
        include_news: bool = True,
        include_financials: bool = True,
    ) -> CreditProfile:
        """
        Generate a comprehensive credit profile for an issuer.

        Args:
            issuer_id: Unique identifier for the issuer
            include_news: Include news sentiment analysis
            include_financials: Include financial metrics analysis

        Returns:
            Complete CreditProfile object
        """
        pass

    @abstractmethod
    def update_profile(
        self,
        existing_profile: CreditProfile,
        new_data: Dict[str, Any],
    ) -> CreditProfile:
        """
        Update an existing profile with new information.

        Args:
            existing_profile: The profile to update
            new_data: New data to incorporate

        Returns:
            Updated CreditProfile
        """
        pass

    @abstractmethod
    def compare_issuers(
        self,
        issuer_ids: List[str],
    ) -> Dict[str, Any]:
        """
        Generate comparative analysis of multiple issuers.

        Args:
            issuer_ids: List of issuer IDs to compare

        Returns:
            Comparative analysis results
        """
        pass


class BaseDocumentProcessor(BaseAnalyzer):
    """
    Abstract base class for document processing.

    Implementations should handle various document types:
    - SEC filings (10-K, 10-Q, 8-K)
    - Earnings call transcripts
    - Rating agency reports
    - Covenant documents
    """

    @abstractmethod
    def process_document(
        self,
        document_path: str,
        document_type: str,
        issuer_id: str,
    ) -> DocumentAnalysisResult:
        """
        Process and analyze a financial document.

        Args:
            document_path: Path to the document
            document_type: Type of document (10-K, 10-Q, etc.)
            issuer_id: Associated issuer

        Returns:
            Analysis result with extracted information
        """
        pass

    @abstractmethod
    def extract_covenants(
        self,
        document_path: str,
    ) -> Dict[str, Any]:
        """
        Extract covenant information from a document.

        Args:
            document_path: Path to covenant document

        Returns:
            Extracted covenant terms and conditions
        """
        pass

    @abstractmethod
    def supported_document_types(self) -> List[str]:
        """
        Get list of supported document types.

        Returns:
            List of document type identifiers
        """
        pass


class BaseNewsAnalyzer(BaseAnalyzer):
    """
    Abstract base class for news analysis.

    Implementations should:
    - Fetch relevant news for issuers
    - Analyze sentiment
    - Identify material events
    - Generate alerts for significant news
    """

    @abstractmethod
    def fetch_news(
        self,
        issuer_id: str,
        days_back: int = 30,
        max_items: int = 50,
    ) -> List[NewsItem]:
        """
        Fetch recent news for an issuer.

        Args:
            issuer_id: Issuer to fetch news for
            days_back: Number of days to look back
            max_items: Maximum news items to return

        Returns:
            List of relevant news items
        """
        pass

    @abstractmethod
    def analyze_sentiment(
        self,
        news_items: List[NewsItem],
    ) -> SentimentScore:
        """
        Analyze aggregate sentiment from news items.

        Args:
            news_items: List of news to analyze

        Returns:
            Overall sentiment score
        """
        pass

    @abstractmethod
    def detect_material_events(
        self,
        news_items: List[NewsItem],
    ) -> List[Dict[str, Any]]:
        """
        Detect material events from news.

        Args:
            news_items: News items to scan

        Returns:
            List of detected material events
        """
        pass

    @abstractmethod
    def generate_news_digest(
        self,
        issuer_id: str,
        period: str = "weekly",
    ) -> str:
        """
        Generate a news digest for an issuer.

        Args:
            issuer_id: Issuer to generate digest for
            period: Time period (daily, weekly, monthly)

        Returns:
            Markdown formatted news digest
        """
        pass
